version: "2.0"
services:
  
  client:
    build:
      context: client/
    image: jerryauvagha/yolo_client:1.0
    container_name: yolo_client
    entrypoint: npm start
    ports:
      - 3000:3000
    tty: true
    networks:
      - yolo_network
    depends_on:
      - backend

  backend:
    build:
      context: backend/
    image: jerryauvagha/yolo_backend:1.0
    container_name: yolo_backend
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/yolomy
    entrypoint: npm start
    ports:
      - 8000:8000
    networks:
      - yolo_network
    tty: true
  
  mongodb:
    image: mongo:latest
    container_name: 'yolo_db'
    volumes:
      - yolo_volume:/data/db
    networks:
      - yolo_network

networks:
  yolo_network:
    driver: bridge

volumes:
  yolo_volume:
