

version: '3.3'

services:
  backend:
    build:
      context: backend/
    image: jerryauvagha/yolo_backend:1.0
    container_name: yolo_backend
    ports:
      - '8000:8000'
    env_file:
      - './backend/.env'
    networks:
      - yolo_network
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0.3
    container_name: 'yolo_db'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - yolo_volume:/data/db
    networks:
      - yolo_network

volumes:
  yolo_volume:

networks:
  yolo_network:
    driver: bridge