

version: '3.3'

services:
  mongo:
    image: mongo:6.0.3
    container_name: 'yolo_db'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - yolo_volume:/data/db
    networks:
      - yolo_network

volumes:
  yolo_volume:

networks:
  yolo_network:
    driver: bridge